### ISSUE TITLE
TypeError: Moderation is not a constructor

### ISSUE THREAD

**Issue by RealSkyr0** [bad-boy-discord/discord-moderation#2]
![image](https://user-images.githubusercontent.com/44062109/124391708-908c9880-dcfa-11eb-866e-f16b64c74de6.png)
Used the JS example provided in this repo, yes I have all the node modules (fs, ms, discord.js, discord-moderation)

**Comment by bad-boy-discord** [comment]
Hello, could you please tell me what you see when you hover over the Moderation Class?

**Comment by RealSkyr0** [comment]
![image](https://user-images.githubusercontent.com/44062109/124391895-7606ef00-dcfb-11eb-8964-ceb7e0035a9b.png)

**Comment by bad-boy-discord** [comment]
Will be fixed in 1.0.7
Thank you!

**Comment by RealSkyr0** [comment]
cool

**Comment by bad-boy-discord** [comment]
Fix is published.
