### ISSUE TITLE
[BR]

### ISSUE THREAD

**Issue by Gaevleflammen** [bad-boy-discord/discord-moderation#4]
ReferenceError at MuteHandler.js:22
![image](https://user-images.githubusercontent.com/69974963/128710735-22e2c668-0cd5-4f55-9d4e-5665e3c24204.png)
discord.js v13.0.1
discord-moderation v1.0.14
node v16.6.1

**Comment by bad-boy-discord** [comment]
Hello! Thanks for help! Bug fixed in 1.015!
