### ISSUE TITLE
[BR] (again. sorry...)

### ISSUE THREAD

**Issue by Gaevleflammen** [bad-boy-discord/discord-moderation#5]
I apologise for bothering you with bug reports. I've sent you a friend request on Discord so that you don't get spammed on GitHub. Anyway, TypeErrors at WarnHandler.js:24:22 and Moderation.js:38:22. "Utils is not a constructor". 
![image](https://user-images.githubusercontent.com/69974963/128737680-e3d7a22b-6701-483b-82a1-27bf2fd29787.png)
I think this is caused by **Utils.js not loading properly** because you've used `this` before `super()`.

node v16.6.1
discord-moderation v1.0.15
discord.js v13.0.1

**Comment by bad-boy-discord** [comment]
Hello again! 
I looked at the module code and realized what my mistake was.
Thank you for reporting bugs!

**Comment by bad-boy-discord** [comment]
Bug fixed in 1.0.16!
